<a href="https://colab.research.google.com/github/teplyikot/DS_python/blob/main/HW1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Numpy. Task1

In [36]:
import numpy as np

In [37]:
a = np.array([[1, 6], [2, 8],[3, 11],[3, 10],[1, 7]])

In [38]:
a

array([[ 1,  6],
       [ 2,  8],
       [ 3, 11],
       [ 3, 10],
       [ 1,  7]])

In [39]:
mean_a = np.array([a.mean(axis=0)])

In [40]:
mean_a

array([[2. , 8.4]])

Numpy. Task2

In [41]:
a_centered = np.array([a - mean_a])

In [42]:
a_centered

array([[[-1. , -2.4],
        [ 0. , -0.4],
        [ 1. ,  2.6],
        [ 1. ,  1.6],
        [-1. , -1.4]]])